
#Tables

#users     : counsellor accounts and salted password hashes
#patients  : simulated patient profiles, each owned by one counsellor
#sessions  : counselling session with a patient with summary and feedback as json
#messages  : every turn of every session

import hashlib
import hmac
import json
import os
import secrets
import sqlite3
from contextlib import contextmanager
from datetime import datetime

DB_PATH = os.getenv("DB_PATH", "counseling.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt          TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS patients (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    age         INTEGER,
    gender      TEXT,
    age_group   TEXT,
    ethnicity   TEXT,
    concerns    TEXT NOT NULL,          -- JSON list of strings
    persona     TEXT NOT NULL,          -- JSON object generated by the LLM
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id  INTEGER NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at  TEXT NOT NULL,
    ended_at    TEXT,
    summary     TEXT,                   -- JSON object, written when session ends
    feedback    TEXT                    -- JSON object, written on request
);

CREATE TABLE IF NOT EXISTS messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id  INTEGER NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('patient', 'counselor')),
    content     TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
"""


@contextmanager
def _conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def init_db():
    with _conn() as c:
        c.executescript(SCHEMA)


# users

def _hash_password(password, salt):
    return hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 200_000).hex() # use actual PBKDF2 hashing for passwds


def create_user(username, password):
    salt = secrets.token_hex(16)
    try:
        with _conn() as c:
            cur = c.execute(
                "INSERT INTO users (username, password_hash, salt, created_at) VALUES (?, ?, ?, ?)",
                (username.strip().lower(), _hash_password(password, salt), salt, datetime.now().isoformat(timespec="seconds")),
            )
            return cur.lastrowid
    except:
        return None


def authenticate(username, password):
    with _conn() as c:
        row = c.execute(
            "SELECT * FROM users WHERE username = ?", (username.strip().lower(),)
        ).fetchone()
    if row and hmac.compare_digest(row["password_hash"], _hash_password(password, row["salt"])): # compares hashes
        return {"id": row["id"], "username": row["username"]}
    return None


# patients

def _patient_from_row(row):
    p = dict(row)
    p["concerns"] = json.loads(p["concerns"])
    p["persona"] = json.loads(p["persona"])
    return p


def create_patient(user_id, gender, age_group, ethnicity, concerns, persona):
    with _conn() as c:
        cur = c.execute(
            """INSERT INTO patients (user_id, name, age, gender, age_group, ethnicity,
                                     concerns, persona, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (user_id, persona.get("name", "Unnamed"), persona.get("age"), gender, age_group,
             ethnicity, json.dumps(concerns), json.dumps(persona), datetime.now().isoformat(timespec="seconds")),
        )
        return cur.lastrowid


def get_patient(patient_id):
    with _conn() as c:
        row = c.execute("SELECT * FROM patients WHERE id = ?", (patient_id,)).fetchone()
    return _patient_from_row(row) if row else None


def list_patients(user_id):
    with _conn() as c:
        rows = c.execute(
            """SELECT p.*,
                      COUNT(s.id) AS session_count,
                      MAX(COALESCE(s.started_at, p.created_at)) AS last_activity
               FROM patients p
               LEFT JOIN sessions s ON s.patient_id = p.id
               WHERE p.user_id = ?
               GROUP BY p.id
               ORDER BY last_activity DESC""",
            (user_id,),
        ).fetchall()
    return [_patient_from_row(r) for r in rows]


def delete_patient(patient_id):
    with _conn() as c:
        c.execute("DELETE FROM patients WHERE id = ?", (patient_id,))


# sessions

def _session_from_row(row):
    s = dict(row)
    s["summary"] = json.loads(s["summary"]) if s["summary"] else None
    s["feedback"] = json.loads(s["feedback"]) if s["feedback"] else None
    return s


def get_or_create_open_session(user_id, patient_id):
    with _conn() as c:
        row = c.execute(
            "SELECT id FROM sessions WHERE patient_id = ? AND user_id = ? AND ended_at IS NULL "
            "ORDER BY id DESC LIMIT 1",
            (patient_id, user_id),
        ).fetchone()
        if row:
            return row["id"]
        cur = c.execute(
            "INSERT INTO sessions (patient_id, user_id, started_at) VALUES (?, ?, ?)",
            (patient_id, user_id, datetime.now().isoformat(timespec="seconds")),
        )
        return cur.lastrowid


def get_session(session_id):
    with _conn() as c:
        row = c.execute("SELECT * FROM sessions WHERE id = ?", (session_id,)).fetchone()
    return _session_from_row(row) if row else None


def list_sessions(patient_id, completed_only = False):
    q = "SELECT * FROM sessions WHERE patient_id = ?"
    if completed_only:
        q += " AND ended_at IS NOT NULL"
    q += " ORDER BY id ASC"
    with _conn() as c:
        rows = c.execute(q, (patient_id,)).fetchall()
    return [_session_from_row(r) for r in rows]


def session_number(session_id):
    """1-based position of this session among the patient's sessions."""
    with _conn() as c:
        row = c.execute(
            """SELECT COUNT(*) AS n FROM sessions
               WHERE patient_id = (SELECT patient_id FROM sessions WHERE id = ?) AND id <= ?""",
            (session_id, session_id),
        ).fetchone()
    return row["n"]


def end_session(session_id, summary):
    with _conn() as c:
        c.execute(
            "UPDATE sessions SET ended_at = ?, summary = ? WHERE id = ?",
            (datetime.now().isoformat(timespec="seconds"), json.dumps(summary) if summary else None, session_id),
        )


def save_feedback(session_id, feedback):
    with _conn() as c:
        c.execute("UPDATE sessions SET feedback = ? WHERE id = ?", (json.dumps(feedback), session_id))


# messages

def add_message(session_id, role, content):
    with _conn() as c:
        c.execute(
            "INSERT INTO messages (session_id, role, content, created_at) VALUES (?, ?, ?, ?)",
            (session_id, role, content, datetime.now().isoformat(timespec="seconds")),
        )


def get_messages(session_id):
    with _conn() as c:
        rows = c.execute(
            "SELECT role, content, created_at FROM messages WHERE session_id = ? ORDER BY id",
            (session_id,),
        ).fetchall()
    return [dict(r) for r in rows]
